Repository ISIS3510-202320-Team13/Flutter, pull requests merged in 2023-11, with the labels that each got.

#21 Feat/near parkings
  android/app/src/main/AndroidManifest.xml
  lib/ui/client/reservation_process/widgets/process_stepper.dart
  lib/ui/home/home_page.dart
  lib/ui/home/near_parkings.dart
  pubspec.lock
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: enhancement, feature

#24 Feat/near parkings
  android/app/src/main/AndroidManifest.xml
  lib/ui/home/home_page.dart
  lib/ui/home/near_parkings.dart
  lib/ui/utils/file_reader.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
Labels: enhancement, feature

#26 Bug fix: near parkings
  assets/transparent.png
  lib/ui/home/home_page.dart
  pubspec.lock
  pubspec.yaml
Labels: bug

#28 Add storage of some preferences
  lib/ui/home/home_page.dart
  lib/ui/utils/file_reader.dart
Labels: enhancement, feature

#37 App telemetry (BQs Type 1)
  lib/logic/reservation/bloc/parking_reservation_bloc.dart
  lib/ui/home/near_parkings.dart
  pubspec.lock
  pubspec.yaml
Labels: feature

#36 App eventual connectivity
  lib/app.dart
  lib/logic/calls/apiCall.dart
  lib/logic/connectivity_check/bloc/connectivity_check_bloc.dart
  lib/logic/connectivity_check/bloc/connectivity_check_event.dart
  lib/logic/connectivity_check/bloc/connectivity_check_state.dart
  lib/logic/reservation/bloc/parking_reservation_bloc.dart
  lib/ui/reservation_process/reservation_process_screen.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: feature
