Repository ISIS3510-202320-Team13/Flutter, pull requests merged in 2023-12, with the labels that each got.

#41 Feat: Use parking repository with near parkings
  lib/data/models/parking.dart
  lib/data/models/reservations/parking.dart
  lib/data/models/reservations/parking_reservation.dart
  lib/data/models/reservations/reservation.dart
  lib/data/repositories/parking_repository.dart
  lib/data/utils/type_conversions.dart
  lib/logic/geolocation/harvesine.dart
  lib/logic/reservation/bloc/parking_reservation_bloc.dart
  lib/ui/home/home_page.dart
  lib/ui/home/near_parkings.dart
  lib/ui/reservation_process/reservation_process_screen.dart
  lib/ui/reservation_process/widgets/parking_view.dart
Labels: enhancement

#48 Optmization
  lib/ui/home/home_page.dart
  lib/ui/home/near_parkings.dart
Labels: enhancement

#51 Added back button in near-parkings view
  lib/ui/home/near_parkings.dart
  pubspec.lock
Labels: bug

#52 Fix: Set location accuracy
  lib/logic/geolocation/bloc/location_bloc.dart
Labels: bug

#53 Add right function to calculate the choice parking
  lib/data/models/parking.dart
  lib/ui/home/near_parkings.dart
  pubspec.lock
Labels: bug

#50 added QR code to ongoing reservations
  assets/darklogo.png
  lib/logic/reservation/reservation_controller.dart
  lib/ui/home/home_page.dart
  lib/ui/home/show_parkingList.dart
  lib/ui/reservation_process/reservation_process_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: feature

#57 Activity bug fixed
  lib/ui/commonFeatures/activity/activity.dart
Labels: bug
